#!/bin/bash -x

cp -rf /opt/default.conf /etc/nginx/conf.d/default.conf
sed -i 's!/var/www/html!/var/www/html/public!' /etc/nginx/conf.d/default.conf
chmod 777 /var/www/html/storage/
chmod 777 /var/www/html/storage/* -R

nginx -s reload