version: "3.4"
services:
  mariadb_1:
    image: registry.digitalocean.com/butchershop/mariadb-build:10.7.1-1
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/mariadb/
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./:/mnt/project/:rw
  nginx:
    user: nginx
    image: registry.digitalocean.com/butchershop/nginx-build:1.21.5.1-alpine
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/nginx-1.21.5/
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/:rw
    depends_on:
      - php_1
  php_1:
    user: www-data
    image: registry.digitalocean.com/butchershop/php-build:8.1.1-1-fqm
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/8.1.1-fqm/
    restart: always
    container_name: php_docker
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/:rw
  phpmyadmin:
    image: registry.digitalocean.com/butchershop/phpmyadmin-build:5.1.1
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/phpmyadmin/
    labels:
      description: "MariaDB"
    restart: always
    environment:
      - PMA_USER
      - PMA_PASSWORD
    ports:
      - 8088:80
    container_name: phpmyadmin
    depends_on:
      - mariadb_1
  redis_1:
    image: redis:6.2.6
    container_name: redis
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
volumes:
  mariadb_data:
  redis_data: