version: "3.4"
services:
  mariadb_1:
    image: mariadb-build:x
    #image: registry.digitalocean.com/butchershop/mariadb-build:10.7.1-1
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/mariadb/
    restart: always
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./:/mnt/project/:rw
  nginx:
    user: root
    image: nginx-build:1.21.5.1-alpine
    #image: registry.digitalocean.com/butchershop/nginx-build:1.21.5.1-alpine
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/nginx-1.21.5/
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/:rw
    depends_on:
      - php
  php:
    user: root
    image: php-build:8.1.2-x1-fqm
    #image: registry.digitalocean.com/butchershop/php-build:8.1.2-1-fqm
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/8.1.1-fqm/
    restart: always
    container_name: php_docker
    expose:
      - 9000
    ports:
      - 9003:9003
    volumes:
      - ./:/var/www/html/:rw
  phpmyadmin:
    image: phpmyadmin-build:5.1.1
    #image: registry.digitalocean.com/butchershop/phpmyadmin-build:5.1.1
    #build:  
    #  dockerfile: Dockerfile
    #  context: ./Compilaciones/phpmyadmin/
    labels:
      description: "MariaDB"
    restart: always
    environment:
      - PMA_USER
      - PMA_PASSWORD
    ports:
      - 8088:80
    container_name: phpmyadmin
    depends_on:
      - mariadb_1
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
volumes:
  mariadb_data:
  redis_data:
