version: "3.4"
services:
  mariadb_1:
    image: mariadb:10.7.1
    restart: always
    container_name: mariadb
    environment:
      - MARIADB_USER=developer
      - MARIADB_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    user: root
    image: nginx-build:1.21.5.1-alpine
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - php_1
  php_1:
    user: root
    image: php-comp:7.4.27.1-fqm
    restart: always
    container_name: php_docker
    expose:
      - 9000
    volumes:
      - ./:/var/www/html:rw
volumes:
  mariadb_data: