#!/bin/bash -x

cd /var/www/html/

npm install
npm run dev

composer install
php artisan key:generate
php artisan migrate

php -r "file_exists('.env') || copy('.env.example', '.env');"

bash /opt/custom_php.sh 2

echo "Laravel Environment has been selected..."